### ISSUE TITLE
Non functional on Magisk 18100

### ISSUE THREAD

**Issue by adsbhatial** [Magisk-Modules-Repo/scr#4]
This module does not work with the latest magisk manager v7.1.1.

The recorder app keeps closing but does not record anything. 
Even after unistalling the module, the app still remains.

Device: Oneplus 5 A5000 Android 9.0 OxygenOS 9.1.4
Magisk: 18100
Manager: 7.1.1

**Comment by crashoverride1995** [comment]
It's working as it should on Magisk 19 Canary build and has been updated to support the newer Magisk template and was earlier working on Magisk 18.1 when I was on it, with v1.1 of the module. I am using it currently on my 3T running Android 9.0 HavocOS 2.4.

**Comment by adsbhatial** [comment]
![Screenshot_20190504-105854](https://user-images.githubusercontent.com/7845422/57174403-fb609180-6e5b-11e9-9959-6645c1babc37.jpg)
This is still not working. I am on the latest Magisk 19100 and the May 3rd Los Recorder update. But the recorder still keeps crashing. I have attached a screenshot for your reference.

Device: Oneplus 5 A5000 Android 9.0 OxygenOS 9.1.5
Magisk: 19100
Manager: 7.1.2

**Comment by crashoverride1995** [comment]
How am I supposed to guess the error from the screenshot, send in a Logcat of the crash. And I am 90% sure it's something that OP messed up in OOS 9, because everything works as expected in all other Pie ROMs.

**Comment by adsbhatial** [comment]
[05-04 10:58:46.016  7242.txt](https://github.com/Magisk-Modules-Repo/scr/files/3145396/05-04.10.58.46.016.7242.txt)
Sorry for not giving out logs.

I have attached the log file. I remember it working on atleast Oxygen OS 9.0.2. But I didnt check exactly when it stopped working

**Comment by crashoverride1995** [comment]
I have made a test version, but I can't guarantee if it'll work or not, if you are willing to test contact me over at telegram @CrashOverride1995.

**Comment by adsbhatial** [comment]
Contacted you on telegram.
